### ISSUE TITLE
Error: Cannot find module './data.json'

### ISSUE THREAD

**Issue by DerEchteMauriice** [Z8pn/GangApp#1]
Hey, warum bekomme ich diesen Fehlercode wenn ich die "Server.js" mit pm2 starte?

Error: Cannot find module './data.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Module.Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:61:29)
    at require (internal/modules/cjs/helpers.js:25:1
    at setAuth (/home/Server/server.js:371:22)
    at Object.<anonymous> (/home/Server/server.js:384:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3) code: 'MODULE_NOT_FOUND' }

**Comment by Z8pn** [comment]
Weil die app versucht die Google-Tabelle aufzurufen und dafür keine Rechte hat.
Eine ".json"-Datei mit der du dich Authentifizieren kannst bekommst du von Google kriegen und musst dieses dann einfügen
https://www.npmjs.com/package/google-spreadsheet

**Comment by DerEchteMauriice** [comment]
Ah okay danke, den Client sollte ich auch am besten auf Ubuntu Builden oder?

**Comment by DerEchteMauriice** [comment]
Sorry fürs nerven.. aber bezüglich des Builden vom Client, ich habe den Client gebuilded aber es kommt die ganze zeit nur grauscreen (https://gyazo.com/daad60dfea531951eb54f7cac0c9aa4b) wärst du nochmal so lieb und würdest mir helfen?
